"""Deterministic C++ header generation for selected uIcons assets."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Dict, List, Sequence

from .catalog import CATALOGS, IconAsset, open_catalog
from .formats import FORMATS, PIXEL_FORMAT_ENUM, analyze, convert, stride, summarize


_IDENTIFIER = re.compile(r"[^A-Za-z0-9_]")


def read_manifest(path: Path) -> Dict[str, Any]:
    """Read and validate a JSON project manifest."""

    try:
        manifest = json.loads(Path(path).read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise ValueError(f"invalid JSON in {path}: {error}") from error
    if not isinstance(manifest, dict):
        raise ValueError(f"manifest {path} must contain a JSON object")
    return manifest


def validate_manifest(manifest: Dict[str, Any]) -> tuple:
    """Return normalized catalog, sizes, format, and icon identifiers."""

    catalog_name = manifest.get("catalog", "fontawesome")
    if catalog_name not in CATALOGS:
        raise ValueError(
            "unsupported catalog {!r}; choose one of: {}".format(catalog_name, ", ".join(CATALOGS))
        )

    sizes = manifest.get("sizes", [16])
    if not isinstance(sizes, list) or not sizes or not all(isinstance(size, int) for size in sizes):
        raise ValueError("manifest 'sizes' must be a non-empty JSON array of integers")
    normalized_sizes = tuple(sorted(set(sizes)))
    if any(size <= 0 for size in normalized_sizes):
        raise ValueError("manifest 'sizes' must contain positive integers")

    output_format = manifest.get("format", "mono-vertical")
    if output_format not in FORMATS:
        raise ValueError(
            "unsupported format {!r}; choose one of: {}".format(output_format, ", ".join(FORMATS))
        )

    icons = manifest.get("icons", [])
    if not isinstance(icons, list) or not all(isinstance(icon, str) and icon for icon in icons):
        raise ValueError("manifest 'icons' must be a JSON array of non-empty strings")
    normalized_icons = tuple(sorted(set(icons)))
    return catalog_name, normalized_sizes, output_format, normalized_icons


def _symbol(asset: IconAsset) -> str:
    name = _IDENTIFIER.sub("_", asset.name).strip("_") or "icon"
    if name[0].isdigit():
        name = "icon_" + name
    return f"{asset.family}_{name}_{asset.width}x{asset.height}"


def _format_bytes(values: Sequence[int]) -> str:
    lines: List[str] = []
    for start in range(0, len(values), 12):
        chunk = values[start : start + 12]
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    return "\n".join(lines)


def render_header(
    assets: Sequence[IconAsset],
    manifest: Dict[str, Any],
    provenance: str = "",
    output_format: str = "mono-vertical",
) -> str:
    """Render a stable C++11 header for the selected assets."""

    lines = [
        "#ifndef UICONS_GENERATED_H",
        "#define UICONS_GENERATED_H",
        "",
        "#include <uicons.h>",
        "",
        "// Generated by uicons. Do not edit; run the generator instead.",
    ]
    if provenance:
        lines.append(f"// Source: {provenance}.")
    lines.extend(
        [
            "",
            "namespace uicons {",
            "namespace generated {",
            "",
        ]
    )
    for asset in assets:
        symbol = _symbol(asset)
        packed = convert(asset.data, asset.width, asset.height, output_format)
        lines.extend(
            [
                f"static const uint8_t {symbol}_data[] UICONS_PROGMEM = {{",
                _format_bytes(packed),
                "};",
                f"static const Icon {symbol}({symbol}_data, {asset.width}, {asset.height},",
                f"                          {stride(asset.width, output_format)}, sizeof({symbol}_data),",
                f"                          {PIXEL_FORMAT_ENUM[output_format]});",
                "",
            ]
        )
    lines.extend(["} // namespace generated", "} // namespace uicons", "", "#endif", ""])
    return "\n".join(lines)


def build(manifest_path: Path, catalog_dir: Path, output_dir: Path) -> Path:
    """Build the selected manifest into one deterministic generated header."""

    manifest = read_manifest(manifest_path)
    _, sizes, output_format, identifiers = validate_manifest(manifest)
    catalog_name = manifest.get("catalog", "fontawesome")
    catalog = open_catalog(catalog_name, catalog_dir)
    unsupported = sorted(set(sizes) - set(catalog.available_sizes))
    if unsupported:
        raise ValueError(
            "sizes {} are unavailable in the {!r} catalog; available sizes: {}".format(
                ", ".join(map(str, unsupported)),
                catalog_name,
                ", ".join(map(str, catalog.available_sizes)),
            )
        )
    canonical_identifiers = tuple(sorted({catalog.normalize_identifier(icon) for icon in identifiers}))
    assets = catalog.resolve_many(canonical_identifiers, sizes)
    header = render_header(assets, manifest, catalog.provenance, output_format)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "uicons_generated.h"
    temporary_path = output_path.with_suffix(".tmp")
    temporary_path.write_text(header, encoding="utf-8", newline="\n")
    temporary_path.replace(output_path)
    return output_path


def report(manifest_path: Path, catalog_dir: Path) -> Dict[str, Any]:
    """Analyze the selected manifest and return deterministic footprint data."""

    manifest = read_manifest(manifest_path)
    catalog_name, sizes, output_format, identifiers = validate_manifest(manifest)
    catalog = open_catalog(catalog_name, catalog_dir)
    unsupported = sorted(set(sizes) - set(catalog.available_sizes))
    if unsupported:
        raise ValueError(
            "sizes {} are unavailable in the {!r} catalog; available sizes: {}".format(
                ", ".join(map(str, unsupported)),
                catalog_name,
                ", ".join(map(str, catalog.available_sizes)),
            )
        )
    canonical_identifiers = tuple(sorted({catalog.normalize_identifier(icon) for icon in identifiers}))
    assets = catalog.resolve_many(canonical_identifiers, sizes)
    rows = [
        analyze(asset.family, asset.name, asset.width, asset.height, asset.data, output_format)
        for asset in assets
    ]
    header = render_header(assets, manifest, catalog.provenance, output_format)
    totals = summarize(rows, len(header.encode("utf-8")))
    return {
        "catalog": catalog_name,
        "format": output_format,
        "provenance": catalog.provenance,
        "icons": rows,
        "totals": totals,
    }


def update_manifest(
    path: Path,
    icons: Sequence[str],
    sizes: Sequence[int] = None,
    output_format: str = None,
    catalog: str = None,
) -> None:
    """Add or remove normalized values while preserving a readable manifest."""

    manifest = read_manifest(path) if Path(path).exists() else {}
    if catalog is not None:
        manifest["catalog"] = catalog
    manifest.setdefault("catalog", "fontawesome")
    if sizes is not None:
        manifest["sizes"] = list(sorted(set(sizes)))
    if output_format is not None:
        manifest["format"] = output_format
    manifest["icons"] = sorted(set(icons))
    validate_manifest(manifest)
    Path(path).write_text(json.dumps(manifest, indent=2, sort_keys=False) + "\n", encoding="utf-8")
