// Draws the generated fas/heart 16x16 icon with Adafruit GFX. The manifest
// uses mono-rowmajor, which is byte-identical to what drawBitmap expects,
// so the generated bytes pass straight through with no buffer or conversion.
#include <Arduino.h>
#include <SPI.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>

#include <uicons.h>

#include <uicons_generated.h>

#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64

Adafruit_SSD1306 display(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, -1);

void setup() {
    display.begin(SSD1306_SWITCHCAPVCC, 0x3C);
    display.clearDisplay();
    const uicons::Icon& heart = uicons::generated::fas_heart_16x16;
    display.drawBitmap(56, 24, heart.data, static_cast<int16_t>(heart.width),
                       static_cast<int16_t>(heart.height), SSD1306_WHITE);
    display.display();
}

void loop() {
}
