#ifndef UICONS_GENERATED_H
#define UICONS_GENERATED_H

#include <uicons.h>

// Generated by uicons. Do not edit; run the generator instead.
// Source: Font Awesome checked-in bitmap catalog (see src/vertical/README.md).

namespace uicons {
namespace generated {

static const uint8_t fas_heart_16x16_data[] UICONS_PROGMEM = {
    0x00, 0x00, 0x3c, 0x3c, 0x7f, 0xfe, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
    0xff, 0xff, 0xff, 0xff, 0x7f, 0xfe, 0x3f, 0xfc, 0x1f, 0xf8, 0x0f, 0xf0,
    0x07, 0xe0, 0x03, 0xc0, 0x01, 0x80, 0x00, 0x00,
};
static const Icon fas_heart_16x16(fas_heart_16x16_data, 16, 16,
                          2, sizeof(fas_heart_16x16_data),
                          PixelFormat::MonoRowMajor);

} // namespace generated
} // namespace uicons

#endif
