#ifndef UICONS_GENERATED_H
#define UICONS_GENERATED_H

#include <uicons.h>

// Generated by uicons. Do not edit; run the generator instead.
// Source: Font Awesome checked-in bitmap catalog (see src/vertical/README.md).

namespace uicons {
namespace generated {

static const uint8_t fas_heart_16x16_data[] UICONS_PROGMEM = {
    0xf8, 0xfc, 0xfe, 0xfe, 0xfe, 0xfe, 0xfc, 0xfc, 0xfc, 0xfc, 0xfe, 0xfe,
    0xfe, 0xfe, 0xfc, 0xf8, 0x00, 0x01, 0x03, 0x07, 0x0f, 0x1f, 0x3f, 0x7f,
    0x7f, 0x3f, 0x1f, 0x0f, 0x07, 0x03, 0x01, 0x00,
};
static const Icon fas_heart_16x16(fas_heart_16x16_data, 16, 16,
                          16, sizeof(fas_heart_16x16_data),
                          PixelFormat::MonoVertical);

} // namespace generated
} // namespace uicons

#endif
